(() => {
  const URL = 'https://kiyneeejluyqzvgdfljt.supabase.co';
  const KEY = 'sb_publishable_NGf9sH1tagHPRfPJRcUvtg_vFJIPF6W';
  const db = window.supabase.createClient(URL, KEY, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } });
  let project, buildings = [], floors = [], items = [], training = [];
  const $ = s => document.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast = text => { const el = $('#toast'); if (!el) return; el.textContent = text; el.classList.remove('hidden'); setTimeout(() => el.classList.add('hidden'), 2800); };

  async function load() {
    const p = await db.from('projects').select('*').eq('name', 'Sekolah Kemala Taruna Bhayangkara').maybeSingle();
    if (p.error) throw p.error; project = p.data;
    if (!project) throw new Error('Jalankan SQL schema Supabase terlebih dahulu.');
    const [b, f, i, t] = await Promise.all([
      db.from('buildings').select('*').eq('project_id', project.id).order('name'),
      db.from('floors').select('*, buildings!inner(project_id)').eq('buildings.project_id', project.id).order('name'),
      db.from('catalog_items').select('*').eq('project_id', project.id).order('name'),
      db.from('training_images').select('*').eq('project_id', project.id).order('created_at', { ascending: false }).limit(100)
    ]);
    for (const result of [b, f, i, t]) if (result.error) throw result.error;
    buildings = b.data || []; floors = f.data || []; items = i.data || []; training = t.data || [];
  }

  function render() {
    const root = $('#admin-content'); if (!root) return;
    root.innerHTML = `<div class="admin-grid">
      <section class="panel admin-card"><div class="panel-header"><div><span class="eyebrow">STRUKTUR PROYEK</span><h2>Gedung & lantai</h2></div><button id="add-building" class="primary-button">Tambah gedung</button></div>
      <div class="admin-list">${buildings.map(b => `<div class="admin-row"><div><strong>${esc(b.name)}</strong><small>${floors.filter(f => f.building_id === b.id).length} lantai</small></div><span><button class="text-button" data-edit-building="${b.id}">Edit</button> <button class="text-button" data-add-floor="${b.id}">+ Lantai</button></span></div>${floors.filter(f => f.building_id === b.id).map(f => `<div class="admin-row admin-child"><div><strong>↳ ${esc(f.name)}</strong></div><button class="text-button" data-edit-floor="${f.id}">Edit</button></div>`).join('')}`).join('') || '<small>Belum ada gedung.</small>'}</div></section>
      <section class="panel admin-card"><div class="panel-header"><div><span class="eyebrow">KATALOG ASET</span><h2>Item</h2></div><button id="add-item" class="primary-button">Tambah item</button></div><div class="admin-list">${items.map(i => `<div class="admin-row"><div><strong>${esc(i.name)}</strong><small>${i.quantity} unit · ${esc(i.description || 'Tanpa deskripsi')}</small></div><button class="text-button" data-edit-item="${i.id}">Edit</button></div>`).join('') || '<small>Belum ada item.</small>'}</div></section></div>
      <section class="panel admin-card"><div class="panel-header"><div><span class="eyebrow">DATASET TRAINING AI</span><h2>Foto referensi</h2><p>File tersimpan di Storage <b>aikon-training</b>, metadatanya di tabel <b>training_images</b>.</p></div></div><form id="photo-form" class="admin-form"><select name="catalog_item_id" required><option value="">Pilih item</option>${items.map(i => `<option value="${i.id}">${esc(i.name)}</option>`).join('')}</select><input name="photo" type="file" accept="image/*" multiple required><button class="primary-button">Simpan foto training</button></form><div class="admin-list">${training.map(t => `<div class="admin-row"><div><strong>${esc(t.label || 'Tanpa label')}</strong><small>${esc(t.status)} · ${esc(t.storage_path)}</small></div></div>`).join('') || '<small>Belum ada foto training.</small>'}</div></section>`;
    $('#add-building')?.addEventListener('click', addBuilding); $('#add-item')?.addEventListener('click', addItem); $('#photo-form')?.addEventListener('submit', upload);
    root.querySelectorAll('[data-add-floor]').forEach(b => b.onclick = () => addFloor(b.dataset.addFloor)); root.querySelectorAll('[data-edit-building]').forEach(b => b.onclick = () => editBuilding(b.dataset.editBuilding)); root.querySelectorAll('[data-edit-floor]').forEach(b => b.onclick = () => editFloor(b.dataset.editFloor)); root.querySelectorAll('[data-edit-item]').forEach(b => b.onclick = () => editItem(b.dataset.editItem));
  }
  async function addBuilding() { const name = prompt('Nama gedung:'); if (!name?.trim()) return; const r = await db.from('buildings').insert({ project_id: project.id, name: name.trim() }); if (r.error) return toast(r.error.message); await load(); render(); }
  async function editBuilding(id) { const row = buildings.find(x => x.id === id); const name = prompt('Nama gedung:', row.name); if (!name?.trim()) return; const r = await db.from('buildings').update({ name: name.trim() }).eq('id', id); if (r.error) return toast(r.error.message); await load(); render(); }
  async function addFloor(building_id) { const name = prompt('Nama lantai:'); if (!name?.trim()) return; const r = await db.from('floors').insert({ building_id, name: name.trim() }); if (r.error) return toast(r.error.message); await load(); render(); }
  async function editFloor(id) { const row = floors.find(x => x.id === id); const name = prompt('Nama lantai:', row.name); if (!name?.trim()) return; const r = await db.from('floors').update({ name: name.trim() }).eq('id', id); if (r.error) return toast(r.error.message); await load(); render(); }
  async function addItem() { const name = prompt('Nama item:'); if (!name?.trim()) return; const quantity = Number(prompt('Jumlah unit:', '1') || 0); const description = prompt('Deskripsi:', '') || null; const building_id = prompt(`ID gedung (opsional):\n${buildings.map(b => `${b.name}: ${b.id}`).join('\n')}`) || null; const floor_id = prompt(`ID lantai (opsional):\n${floors.map(f => `${f.name}: ${f.id}`).join('\n')}`) || null; const r = await db.from('catalog_items').insert({ project_id: project.id, name: name.trim(), quantity, description, building_id, floor_id }); if (r.error) return toast(r.error.message); await load(); render(); }
  async function editItem(id) { const row = items.find(x => x.id === id); const name = prompt('Nama item:', row.name); if (!name?.trim()) return; const quantity = Number(prompt('Jumlah unit:', row.quantity) || 0); const description = prompt('Deskripsi:', row.description || '') || null; const r = await db.from('catalog_items').update({ name: name.trim(), quantity, description, updated_at: new Date().toISOString() }).eq('id', id); if (r.error) return toast(r.error.message); await load(); render(); }
  async function upload(event) { event.preventDefault(); const form = new FormData(event.currentTarget), itemId = form.get('catalog_item_id'), user = (await db.auth.getUser()).data.user; for (const file of form.getAll('photo')) { const path = `${project.id}/${itemId}/${crypto.randomUUID()}-${file.name}`; const up = await db.storage.from('aikon-training').upload(path, file); if (up.error) return toast(up.error.message); const r = await db.from('training_images').insert({ project_id: project.id, catalog_item_id: itemId, storage_path: path, label: items.find(i => i.id === itemId)?.name || file.name, status: 'pending', created_by: user?.id }); if (r.error) return toast(r.error.message); } await load(); render(); toast('Foto training tersimpan.'); }
  async function init() { const { data: { user } } = await db.auth.getUser(); if (!user) return; const p = await db.from('profiles').select('role').eq('id', user.id).single(); if (p.error || p.data?.role !== 'admin') return; const nav = document.querySelector('[data-route="catalog"]')?.parentElement; if (nav && !document.querySelector('[data-route="admin"]')) nav.insertAdjacentHTML('beforeend', '<a href="#admin" class="nav-link" data-route="admin"><span class="nav-icon">⚙</span><span>Admin catalog</span></a>'); const content = $('.content'); if (!content || $('#admin')) return; content.insertAdjacentHTML('beforeend', '<section id="admin" class="view"><div class="page-header"><div><span class="eyebrow">ADMINISTRATOR</span><h1>Kelola project & katalog</h1><p>Sekolah Kemala Taruna Bhayangkara · Gunung Sindur, Bogor</p></div></div><div id="admin-content"></div></section>'); document.querySelector('[data-route="admin"]').onclick = e => { e.preventDefault(); document.querySelectorAll('.view').forEach(v => v.classList.toggle('active', v.id === 'admin')); load().then(render).catch(x => toast(x.message)); }; }
  document.addEventListener('DOMContentLoaded', () => setTimeout(() => init().catch(console.error), 1000));
})();
